const num1 = 10.50;
const num2 = 10.36;
const soma = num1 + num2;
const sub = num1 - num2
const mult = num1 * num2
const div = num1 / num2
console.log(`${num1} + ${num2} = ${soma}\n 
${num1} X ${num2} = ${mult}\n
${num1} - ${num2} = ${sub.toFixed(2)}\n
${num1} / ${num2} = ${div.toFixed(2)}`);
